include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: true
    prefer_const_constructors: true
    require_trailing_commas: true
    always_declare_return_types: true