---
name: purple_task
description: Simple TO-DO app to help you get stuff done
publish_to: none
version: 2.0.0
environment:
  sdk: ^3.5.3
dependencies:


#  window_size:
#    git:
#      url: git://github.com/google/flutter-desktop-embedding.git
#      path: plugins/window_size
#      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3
  ant_icons:
    path: packages/ant_icons
  collection: 1.19.0
  drift: ^2.22.1
  drift_flutter: ^0.2.2
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_staggered_animations: ^1.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  intl: ^0.20.0
  path: 1.9.0
  path_provider: any
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.0.2
  very_good_analysis: ^7.0.0
dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  drift_dev: ^2.22.1
  effective_dart: ^1.3.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
flutter:
  uses-material-design: true
  assets:
  - assets/images/
