---
name: purple_task
description: Simple TO-DO app to help you get stuff done
publish_to: none
version: 1.3.2
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  intl: ^0.20.0
  url_launcher: ^6.0.2
#  window_size:
#    git:
#      url: git://github.com/google/flutter-desktop-embedding.git
#      path: plugins/window_size
#      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3
  ant_icons:
    path: packages/ant_icons
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  path_provider: any
  riverpod_annotation: ^2.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  effective_dart: ^1.3.1
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
flutter:
  uses-material-design: true
  assets:
  - assets/images/
