---
name: purple_task
description: Simple TO-DO app to help you get stuff done
publish_to: none
version: 1.2.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.1
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  intl: ^0.16.1
  url_launcher: ^5.6.0
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3
  # local package
  ant_icons:
    path: packages/ant_icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: null
flutter:
  uses-material-design: true
  assets:
    - assets/images/
