  name: purple-task
  version: 1.3.0
  summary: Simple TO-DO app to help you get stuff done
  description: Purple Task is
  confinement: strict
  base: core18
  apps:
    purple-task:
      command: to_do
      extensions: [flutter-beta]
  parts:
    purple-task:
      source: .
      plugin: flutter
      flutter-target: lib/main.dart
