  name: purple-task
  version: 1.3.2
  summary: Simple TO-DO app to help you get stuff done
  description: Purple Task is
  confinement: strict
  base: core18

  compression: lzo

  apps:
    purple-task:
      command: to_do
      extensions: [flutter-beta]
  parts:
    purple-task:
      source: .
      plugin: flutter
      flutter-target: lib/main.dart
      stage-packages:
      - libegl1
      - libegl1-mesa
      - libc6
